In [345]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
x = [[1,2,3],   #x는 학습용, y는 정답
    [11, 12, 13]]
y = [0,1]
clf.fit(x, y) #학습시킴

RandomForestClassifier(random_state=0)

In [346]:
clf.predict(x)  # 예측한 데이터를 다시 넣음, 이런짓하지 말자...ㅜ

array([0, 1])

In [347]:
clf.predict([[4,5,6],[14,15,16]])  # 일반적으로 데이터는 전체데이터를 7:3의 비율로 학습데이터와 테스트 데이터로 나눠서 진행한다

array([0, 1])

In [348]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score  #정확도 측정 모듈
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')

In [349]:
iris_data =load_iris()
print(iris_data.keys())
print('='*50)
print(iris_data.feature_names, type(iris_data.feature_names)) # 컬럼명
print('='*50)
print(iris_data.data, type(iris_data.data))                   #학습데이터 실제 값
print('='*50)
print(iris_data.target_names, type(iris_data.target_names))  #컬럼명
print('='*50)
print(iris_data.target, type(iris_data.target))              #정답 레이블 실제 값
df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] <class 'list'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1

In [350]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [351]:
df.describe()  #대략적인 데이터 분포도

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [352]:
pd.Series(iris_data.target).value_counts()  

2    50
1    50
0    50
dtype: int64

In [353]:
dt_model = DecisionTreeClassifier()

x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=11) 
 # 문제용 (훈련, 학습), 정답용(훈련, 학습)
#훈련용과 테스트용 데이터 분리 (7:3)


train_data = iris_data.data
target_data = iris_data.target

In [354]:
dt_model.fit(x_train, y_train)  #해당 모델로 훈련, 학습완료
dt_model_pred = dt_model.predict(x_test) # 문제로 시험보기 (D.T 알고리즘이 정답을 제출함)
score = accuracy_score(y_test, dt_model_pred) # 모델이 낸 답안지와 데스트용 답안지 비교 : 정확도 확인
print(round(score, 4))  #91% 정확도 도출 
#정확도가 너무 높은 경우, 과대적합(OverFitting)의 문제가 발생했다고 볼 수 있다. 혹은 데이터양이 너무 작아 정확도를 신뢰하기 어렵다. 

0.9111


## K-fold cross validation (K겹 교차 검증)

In [355]:
from sklearn.model_selection import KFold
import numpy as np

from inspect import signature

In [356]:
iris_data = load_iris()  #데이터 변경가능성 있어 온전한 데이터로 다시 불러온다. 

kfold = KFold(n_splits=5) #데이터를 5등분한다. 즉 150개 레코드를 30개씩 묶는다. 
signature(KFold)

<Signature (n_splits=5, *, shuffle=False, random_state=None)>

In [357]:
scores = []
for idx_train, idx_test in kfold.split(iris_data):
    x_train, x_test = iris_data.data[idx_train], iris_data.data[idx_test]   
    y_train, y_test = iris_data.target[idx_train], iris_data.target[idx_test]
    
    
# KFold는 트레이닝 들어갈 인덱스와, 테스트용 인덱스 2개를 반환한다.     
# 반환된 것을 훈련용과 테스트용으로 구분하여 담는다. 

In [358]:
dt_model.fit(x_train, y_train)  
dt_model_pred = dt_model.predict(x_test) 
score = accuracy_score(y_test, dt_model_pred)
scores.append(score)
print(round(score, 4),'\n', x_train.shape[0], '\n', x_test.shape[0], '\n')
# 이어서 학습하고 테스트해서 정확도를 검사한다. 

1.0 
 6 
 1 



In [359]:
print('평균 accuracy : ', np.mean(scores))  
# 평균 accuracy :  1.0  결과가 100% 정확도를 나타낸다. 이유를 살펴보면, 정답 데이터가 이미 0,1로 순서대로 정렬되어 있다. 
# 따라서, 이미 정리된 데이터(00000...11111)를 30개씩 나눠서 돌린 결과가 나온것이다. 

평균 accuracy :  1.0


In [360]:
# 작은 구성비를 가진 데이터들이 모두 Train 또는 Test데이터로 분리된 경우 제대로 학습과 테스트를 진행할 수가 없다.
# 따라서, 구성 비가 다른 불균형 데이터를 다룰 때는 Stratified가 붙은 클래스를 이용하거나 stratify옵션을 켜야한다.

from sklearn.model_selection import StratifiedKFold

In [361]:
iris = load_iris()

x_iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
y_iris_df = pd.DataFrame(data=iris.target, columns=['label'])  # 정답지 
print(x_iris_df.shape)
print(y_iris_df.value_counts())

(150, 4)
label
2        50
1        50
0        50
dtype: int64


In [362]:
from sklearn.model_selection import cross_val_score
iris = load_iris()

x_iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
y_iris_df = pd.DataFrame(data=iris.target, columns=['label'])  # 정답지 

scores = cross_val_score(dt_model, x_iris_df, y_iris_df, scoring='accuracy', cv=3)
print(scores)
print(np.mean(scores))

[0.98 0.94 1.  ]
0.9733333333333333


## 하이퍼파라미터(Hyperparameter) 튜닝하기
### sklearn.model_selection.GridSearchCV

In [363]:
from sklearn.model_selection import GridSearchCV

In [364]:
iris_data = load_iris()
x_iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
y_iris_df = pd.DataFrame(data=iris.target, columns=['label'])

x_train, x_test, y_train, y_test = train_test_split(x_iris_df, y_iris_df, test_size=0.3, random_state=11) 
dt_model = DecisionTreeClassifier()

In [365]:
# param_grid 넘겨줄 하이퍼 파라미터 설정 
params = {'max_depth' : [1,3,5],
         'min_samples_split':[1,2,3]}

GCV = GridSearchCV(dt_model, param_grid=params, refit=True, cv=3, scoring="accuracy")
# refit을 True로 설정하였기 때문에, 가장 최적의 파라미터를 찾아 고정된다. 


# 참고>
#class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, iid='deprecated', refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html?highlight=gridsearchcv#sklearn.model_selection.GridSearchCV

In [366]:
GCV.fit(x_train, y_train)  # 학습완료 


print(GCV)  # GCV 가 하나의 모델이 되어 있음. 
print('='*80)
# print(GCV.cv_results_)
df= pd.DataFrame(data= GCV.cv_results_)
print(df.info())
print('-'*80)
print(df.head())
print('='*80)
print(GCV.best_score_)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 3, 5],
                         'min_samples_split': [1, 2, 3]},
             scoring='accuracy')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean_fit_time            9 non-null      float64
 1   std_fit_time             9 non-null      float64
 2   mean_score_time          9 non-null      float64
 3   std_score_time           9 non-null      float64
 4   param_max_depth          9 non-null      object 
 5   param_min_samples_split  9 non-null      object 
 6   params                   9 non-null      object 
 7   split0_test_score        6 non-null      float64
 8   split1_test_score        6 non-null      float64
 9   split2_test_score        6 non-null      float64
 10  mean_test_score          6 non-null      float64
 1

In [367]:
best_model = GCV.best_estimator_
best_pred = dt_model.predict(x_test)
best_score = accuracy_score(y_test, best_pred)
print(best_score)

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [368]:
from sklearn.model_selection import GridSearchCV
iris_data = load_iris()
X_iris_df = pd.DataFrame(data= iris_data.data, columns=iris_data.feature_names)
y_iris_df = pd.DataFrame(data= iris_data.target, columns=["label"])
#하이퍼파라미터튜닝을 중점적으로(알고리즘의 속성값 튜닝)
# min_samples_split:int or float, default = 2 default값이 클수록 뎁스가 얕은 것.
#니들이 정해준대로 학습할테니 수치를 정해줘
# dt_model = DecisionTreeClassifier()
X_train,X_test,Y_train, Y_test =train_test_split(X_iris_df, y_iris_df, test_size = 0.3, random_state=11)
dt_model = DecisionTreeClassifier()
# print(X_train)
# print(y_train)
# max_depth
# min_samples_splitint

#pram_grid에 넘겨줄 하이퍼 파라미터
params = {'max_depth' : [ 1,3,5],
          'min_samples_split':[1,2,3]
         }
GCV = GridSearchCV(dt_model,param_grid=params,refit=True, cv=3, scoring='accuracy')
GCV.fit(X_train, y_train) 

#학습완료,GCV안에 모든걸 다 가지고 있다. 다 따로 밖에서 score이 몇점인지 산술할 필요가 없다.
# print(GCV.cv_results_)
df = pd.DataFrame(data=GCV.cv_results_)
print(df.info())
print(df.head())
print(GCV.best_params_)
print(GCV.best_score_)
# 다음 명령을 사용하여 추가 차원을 np.array()정의 X하거나 나중에 추가 차원을 제거 할 때 추가 목록을 제거하십시오 
# X = X.reshape(X.shape[1:]). 이제 모양은 X(6, 29)입니다.
# 트랜스 X실행 X = X.transpose()의 샘플 같은 수를 얻을 수 X및 Y. 자, 모양X (29, 6)이고 모양은 Y(29,)입니다.

##가장 좋은 형태
# print(X_test)
best_model = GCV.best_estimator_
best_pred = best_model.predict(X_test)
best_score = accuracy_score(y_test, best_pred)
print(best_score)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean_fit_time            9 non-null      float64
 1   std_fit_time             9 non-null      float64
 2   mean_score_time          9 non-null      float64
 3   std_score_time           9 non-null      float64
 4   param_max_depth          9 non-null      object 
 5   param_min_samples_split  9 non-null      object 
 6   params                   9 non-null      object 
 7   split0_test_score        6 non-null      float64
 8   split1_test_score        6 non-null      float64
 9   split2_test_score        6 non-null      float64
 10  mean_test_score          6 non-null      float64
 11  std_test_score           6 non-null      float64
 12  rank_test_score          9 non-null      int32  
dtypes: float64(9), int32(1), object(3)
memory usage: 1.0+ KB
None
   mean_fit_time  std_

In [1]:
from sklearn.model_selection import GridSearchCV
dataset = load_breast_cancer()
X_df = pd.DataFrame(data= dataset .data, columns=iris_data.feature_names)
y_df = pd.DataFrame(data= dataset.target, columns=["label"])
#하이퍼파라미터튜닝을 중점적으로(알고리즘의 속성값 튜닝)
# min_samples_split:int or float, default = 2 default값이 클수록 뎁스가 얕은 것.
#니들이 정해준대로 학습할테니 수치를 정해줘
# dt_model = DecisionTreeClassifier()
X_train,X_test,Y_train, Y_test =train_test_split(X_iris_df, y_iris_df, test_size = 0.3, random_state=11)
dt_model = DecisionTreeClassifier()
# print(X_train)
# print(y_train)
# max_depth
# min_samples_splitint

#pram_grid에 넘겨줄 하이퍼 파라미터
params = {'max_depth' : [ 1,3,5],
          'min_samples_split':[1,2,3]
         }
GCV = GridSearchCV(dt_model,param_grid=params,refit=True, cv=3, scoring='accuracy')
GCV.fit(X_train, y_train) 

#학습완료,GCV안에 모든걸 다 가지고 있다. 다 따로 밖에서 score이 몇점인지 산술할 필요가 없다.
# print(GCV.cv_results_)
df = pd.DataFrame(data=GCV.cv_results_)
print(df.info())
print(df.head())
print(GCV.best_params_)
print(GCV.best_score_)
# 다음 명령을 사용하여 추가 차원을 np.array()정의 X하거나 나중에 추가 차원을 제거 할 때 추가 목록을 제거하십시오 
# X = X.reshape(X.shape[1:]). 이제 모양은 X(6, 29)입니다.
# 트랜스 X실행 X = X.transpose()의 샘플 같은 수를 얻을 수 X및 Y. 자, 모양X (29, 6)이고 모양은 Y(29,)입니다.

##가장 좋은 형태
# print(X_test)
best_model = GCV.best_estimator_
best_pred = best_model.predict(X_test)
best_score = accuracy_score(y_test, best_pred)
print(best_score)

NameError: name 'load_breast_cancer' is not defined